saleor_pos/saleor/dashboard/discount/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sale/$', views.sale_list, name='sale-list'),
    url(r'sale/(?P<pk>[0-9]+)/$', views.sale_edit, name='sale-update'),
    url(r'sale/add/$', views.sale_edit, name='sale-add'),
    url(r'sale/(?P<pk>[0-9]+)/delete/$', views.sale_delete, name='sale-delete'),

    url(r'voucher/$', views.voucher_list, name='voucher-list'),
    url(r'voucher/(?P<pk>[0-9]+)/$', views.voucher_edit, name='voucher-update'),
    url(r'voucher/add/$', views.voucher_edit, name='voucher-add'),
    url(r'voucher/(?P<pk>[0-9]+)/delete/$', views.voucher_delete, name='voucher-delete'),
]

saleor_pos/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

saleor_pos/saleor/dashboard/sites/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='site-index'),
    url(r'^(?P<site_id>[0-9]+)/edit/$', views.update, name='site-update'),
]

saleor_pos/saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .search.urls import urlpatterns as search_urls
from .sites.urls import urlpatterns as site_urls
from .shipping.urls import urlpatterns as shipping_urls
from .users.urls import urlpatterns as users_urls
from .permgroups.urls import urlpatterns as group_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^users/', include(users_urls)),
    url(r'^perms/', include(group_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^search/', include(search_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
]

saleor_pos/saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
   
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor_pos/saleor/discount/models.py
from __future__ import unicode_literals
from datetime import date
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.db.models import F
from django.utils.translation import pgettext, pgettext_lazy
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django_countries import countries
from django_prices.models import PriceField
from django_prices.templatetags.prices_i18n import net
from prices import FixedDiscount, percentage_discount, Price

from ..cart.utils import (
    get_product_variants_and_prices, get_category_variants_and_prices)


class NotApplicable(ValueError):
    pass


class VoucherQueryset(models.QuerySet):

    def active(self):
        today = date.today()
        queryset = self.filter(
            models.Q(usage_limit__isnull=True) |
            models.Q(used__lt=models.F('usage_limit')))
        queryset = queryset.filter(
            models.Q(end_date__isnull=True) | models.Q(end_date__gte=today))
        queryset = queryset.filter(start_date__lte=today)
        return queryset

    def increase_usage(self, voucher):
        voucher.used = F('used') + 1
        voucher.save(update_fields=['used'])

    def decrease_usage(self, voucher):
        voucher.used = F('used') - 1
        voucher.save(update_fields=['used'])


@python_2_unicode_compatible
class Voucher(models.Model):

    APPLY_TO_ONE_PRODUCT = 'one'
    APPLY_TO_ALL_PRODUCTS = 'all'

    APPLY_TO_PRODUCT_CHOICES = (
        (APPLY_TO_ONE_PRODUCT,
         pgettext_lazy('Voucher application', 'Apply to a single item')),
        (APPLY_TO_ALL_PRODUCTS,
         pgettext_lazy('Voucher application', 'Apply to all matching products')))

    DISCOUNT_VALUE_FIXED = 'fixed'
    DISCOUNT_VALUE_PERCENTAGE = 'percentage'

    DISCOUNT_VALUE_TYPE_CHOICES = (
        (DISCOUNT_VALUE_FIXED,
         pgettext_lazy('Voucher discount type', settings.DEFAULT_CURRENCY)),
        (DISCOUNT_VALUE_PERCENTAGE, pgettext_lazy('Voucher discount type', '%')))

    PRODUCT_TYPE = 'product'
    CATEGORY_TYPE = 'category'
    SHIPPING_TYPE = 'shipping'
    VALUE_TYPE = 'value'

    TYPE_CHOICES = (
        (VALUE_TYPE, pgettext_lazy('Voucher: discount for', 'All purchases')),
        (PRODUCT_TYPE, pgettext_lazy('Voucher: discount for', 'One product')),
        (CATEGORY_TYPE, pgettext_lazy('Voucher: discount for', 'A category of products')),
        (SHIPPING_TYPE, pgettext_lazy('Voucher: discount for', 'Shipping')))

    type = models.CharField(
        pgettext_lazy('Voucher field', 'discount for'), max_length=20,
        choices=TYPE_CHOICES, default=VALUE_TYPE)
    name = models.CharField(
        pgettext_lazy('Voucher field', 'name'), max_length=255, null=True,
        blank=True)
    code = models.CharField(
        pgettext_lazy('Voucher field', 'code'), max_length=12, unique=True,
        db_index=True)
    usage_limit = models.PositiveIntegerField(
        pgettext_lazy('Voucher field', 'usage limit'), null=True, blank=True)
    used = models.PositiveIntegerField(default=0, editable=False)
    start_date = models.DateField(
        pgettext_lazy('Voucher field', 'start date'), default=date.today)
    end_date = models.DateField(
        pgettext_lazy('Voucher field', 'end date'), null=True, blank=True)

    discount_value_type = models.CharField(
        pgettext_lazy('Voucher field', 'discount type'), max_length=10,
        choices=DISCOUNT_VALUE_TYPE_CHOICES, default=DISCOUNT_VALUE_FIXED)
    discount_value = models.DecimalField(
        pgettext_lazy('Voucher field', 'discount value'), max_digits=12,
        decimal_places=2)

    # not mandatory fields, usage depends on type
    product = models.ForeignKey(
        'product.Product', blank=True, null=True,
        verbose_name=pgettext_lazy('Voucher field', 'product'))
    category = models.ForeignKey(
        'product.Category', blank=True, null=True,
        verbose_name=pgettext_lazy('Voucher field', 'category'))
    apply_to = models.CharField(
        pgettext_lazy('Voucher field', 'apply to'),
        max_length=20, blank=True, null=True)
    limit = PriceField(
        pgettext_lazy('Voucher field', 'limit'),
        max_digits=12, decimal_places=2, null=True,
        blank=True, currency=settings.DEFAULT_CURRENCY)

    objects = VoucherQueryset.as_manager()

    @property
    def is_free(self):
        return (self.discount_value == Decimal(100) and
                self.discount_value_type == Voucher.DISCOUNT_VALUE_PERCENTAGE)

    class Meta:
        verbose_name = pgettext_lazy('Voucher model', 'voucher')
        verbose_name_plural = pgettext_lazy('Voucher model', 'vouchers')

    def __str__(self):
        if self.name:
            return self.name
        discount = '%s %s' % (
            self.discount_value, self.get_discount_value_type_display())
        if self.type == Voucher.SHIPPING_TYPE:
            if self.is_free:
                return pgettext('Voucher type', 'Free shipping')
            else:
                return pgettext('Voucher type', '%(discount)s off shipping') % {
                    'discount': discount}
        if self.type == Voucher.PRODUCT_TYPE:
            return pgettext('Voucher type', '%(discount)s off %(product)s') % {
                'discount': discount, 'product': self.product}
        if self.type == Voucher.CATEGORY_TYPE:
            return pgettext('Voucher type', '%(discount)s off %(category)s') % {
                'discount': discount, 'category': self.category}
        return pgettext('Voucher type', '%(discount)s off') % {'discount': discount}

    def get_apply_to_display(self):
        if self.type == Voucher.SHIPPING_TYPE and self.apply_to:
            return countries.name(self.apply_to)
        if self.type == Voucher.SHIPPING_TYPE:
            return pgettext('Voucher', 'Any country')
        if self.apply_to and self.type in {
                Voucher.PRODUCT_TYPE, Voucher.CATEGORY_TYPE}:
            choices = dict(self.APPLY_TO_PRODUCT_CHOICES)
            return choices[self.apply_to]

    def get_fixed_discount_for(self, amount):
        if self.discount_value_type == self.DISCOUNT_VALUE_FIXED:
            discount_price = Price(net=self.discount_value,
                                   currency=settings.DEFAULT_CURRENCY)
            discount = FixedDiscount(
                amount=discount_price, name=smart_text(self))
        elif self.discount_value_type == self.DISCOUNT_VALUE_PERCENTAGE:
            discount = percentage_discount(
                value=self.discount_value, name=smart_text(self))
            fixed_discount_value = amount - discount.apply(amount)
            discount = FixedDiscount(
                amount=fixed_discount_value, name=smart_text(self))
        else:
            raise NotImplementedError('Unknown discount value type')
        if discount.amount > amount:
            return FixedDiscount(amount, name=smart_text(self))
        else:
            return discount

    def validate_limit(self, value):
        limit = self.limit if self.limit is not None else value
        if value < limit:
            msg = pgettext(
                'Voucher not applicable',
                'This offer is only valid for orders over %(amount)s.')
            raise NotApplicable(msg % {'amount': net(limit)})

    def get_discount_for_checkout(self, checkout):
        if self.type == Voucher.VALUE_TYPE:
            cart_total = checkout.get_subtotal()
            self.validate_limit(cart_total)
            return self.get_fixed_discount_for(cart_total)

        elif self.type == Voucher.SHIPPING_TYPE:
            if not checkout.is_shipping_required:
                msg = pgettext(
                    'Voucher not applicable', 'Your order does not require shipping.')
                raise NotApplicable(msg)
            shipping_method = checkout.shipping_method
            if not shipping_method:
                msg = pgettext(
                    'Voucher not applicable', 'Please select a shipping method first.')
                raise NotApplicable(msg)
            if (self.apply_to and
                    shipping_method.country_code != self.apply_to):
                msg = pgettext(
                    'Voucher not applicable', 'This offer is only valid in %(country)s.')
                raise NotApplicable(msg % {
                    'country': self.get_apply_to_display()})
            cart_total = checkout.get_subtotal()
            self.validate_limit(cart_total)
            return self.get_fixed_discount_for(shipping_method.price)

        elif self.type in (Voucher.PRODUCT_TYPE, Voucher.CATEGORY_TYPE):
            if self.type == Voucher.PRODUCT_TYPE:
                prices = list(
                    (item[1] for item in get_product_variants_and_prices(
                        checkout.cart, self.product)))
            else:
                prices = list(
                    (item[1] for item in get_category_variants_and_prices(
                        checkout.cart, self.category)))
            if len(prices) == 0:
                msg = pgettext(
                    'Voucher not applicable',
                    'This offer is only valid for selected items.')
                raise NotApplicable(msg)
            if self.apply_to == Voucher.APPLY_TO_ALL_PRODUCTS:
                discounts = (
                    self.get_fixed_discount_for(price) for price in prices)
                discount_total = sum(
                    (discount.amount for discount in discounts),
                    Price(0, currency=settings.DEFAULT_CURRENCY))
                return FixedDiscount(discount_total, smart_text(self))
            else:
                product_total = sum(
                    prices, Price(0, currency=settings.DEFAULT_CURRENCY))
                return self.get_fixed_discount_for(product_total)

        else:
            raise NotImplementedError('Unknown discount type')


@python_2_unicode_compatible
class Sale(models.Model):

saleor_pos/saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor_pos/saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from ..views import staff_member_required
from ...core.utils import get_paginator_items
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))
    customers = get_paginator_items(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor_pos/templates/dashboard/discount/sale_form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% if sale.pk %}
    {{ sale }}
  {% else %}
    {% trans "Add new sale"  context "Sale (discount) page title" %}
  {% endif %} 
  - {% trans "Sales" context "Dashboard sales (discounts) list." %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-sales{% endblock %}

{% block menu_sales_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:sale-list" as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block header_extra %}
  {% if sale.pk %}
    <a class="dropdown-button right" href="#" data-activates="sale-delete"
    data-constrainwidth="false">
      <svg data-src="{% static "dashboard/images/more_vert.svg" %}" height="24" width="24" />
    </a>
    <ul id="sale-delete" class="dropdown-content">
      <li>
        <a class="modal-trigger-custom" href="#base-modal"
        data-href="{% url 'dashboard:sale-delete' pk=sale.pk %}">
          {% trans "Remove sale" context "Sale (discount) action" %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:sale-list' %}">
        {% trans "Sales" context "Dashboard sales (discounts) list." %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:sale-list' %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% if sale.pk %}
          {{ sale }}
        {% else %}
          {% trans "Add new sale" context "Sale (discount) breadcrumbs" %}
        {% endif %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data" id="form-sales" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            <div class="row">
              {{ form.name|materializecss }}
            </div>
            <div class="row">
              <div class="col s12 m8">
                <div class="row">
                  {{ form.value|materializecss }}
                </div>
              </div>
              <div class="col s12 m4">
                {{ form.type|materializecss:"input-field s12" }}
              </div>
            </div>
            <div class="row">
              {{ form.products|materializecss }}
            </div>
            <div class="row">
              {{ form.categories|materializecss }}
            </div>
          </div>

          <div class="card-action right-align">
            {% if sale.pk %}
              <a href="{% url 'dashboard:sale-list' %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect waves-light">
                {% trans "Update" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:sale-list' %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect waves-light">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% endblock %}

saleor_pos/templates/dashboard/discount/sale_list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load materializecss %}

{% block title %}
  {% trans "Sales" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-sales{% endblock %}

{% block menu_sales_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">{% trans "Sales" context "Dashboard sales (discounts) list." %}</li>
  </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block content %}
  <div class="card">
    <div class="data-table-header-action">
      <a href="{% url 'dashboard:sale-add' %}" class="btn-data-table btn-flat"  title="{% trans "Add sale" context "Sale (discount) list add button text" %}">
        {% trans "Add" context "Dashboard add action" %}
      </a>
    </div>
    <div class="data-table-container">
      <table class="bordered highlight responsive data-table">
        <thead>
          <tr>
            <th>
              {% trans "Name" context "Sale (discount) table header" %}
            </th>
            <th>
              {% trans "Discount" context "Sale (discount) table header" %}
            </th>
          </tr>
        </thead>
        <tbody>
          {% if sales %}
            {% for sale in sales %}
              <tr data-action-go="{% url 'dashboard:sale-update' pk=sale.pk %}">
                <td>
                  {{ sale }}
                </td>
                <td>
                  {{ sale.value }}{{ sale.get_type_display }}
                </td>
              </tr>
            {% endfor %}
          {% else %}
          <tr>
            <td>
              <span>
                {% trans "No sales found" context "Empty sales table message" %}
              </span>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
  {% include "dashboard/includes/_pagination.html" %}
{% endblock %}

saleor_pos/templates/dashboard/discount/voucher_form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% if voucher.pk %}
    {{ voucher }}
  {% else %}
    {% trans "Add new voucher" context "Voucher page title" %}
  {% endif %}
   - {% trans "Vouchers" context "Dashboard vouchers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-vouchers{% endblock %}

{% block menu_vouchers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:voucher-list" as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block header_extra %}
  {% if voucher.pk %}
    <a class="dropdown-button right" href="#" data-activates="voucher-delete"
    data-constrainwidth="false">
      <svg data-src="{% static "dashboard/images/more_vert.svg" %}" height="24" width="24" />
    </a>
    <ul id="voucher-delete" class="dropdown-content">
      <li>
        <a class="modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:voucher-delete' pk=voucher.pk %}">
          {% trans "Remove voucher" context "Voucher action" %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:voucher-list' %}">
        {% trans "Vouchers" context "Dashboard vouchers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:voucher-list' %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% if voucher.pk %}
          {{ voucher }}
        {% else %}
          {% trans "Add new voucher" context "Voucher breadcrumbs" %}
        {% endif %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data" id="form-vouchers" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            {% if form.non_field_errors %}
              <blockquote>
                {% for non_field_error in form.non_field_errors %}
                  {{ non_field_error }}
                {% endfor %}
              </blockquote>
            {% endif %}
            <div class="row">
              <div class="col s12 m8">
                <div class="row">
                  {{ form.code|materializecss }}
                </div>
                <div class="row">
                  {{ form.name|materializecss }}
                </div>
                <div class="row">
                  <div class="col s12 m8">
                    <div class="row">
                      {{ form.discount_value|materializecss }}
                    </div>
                  </div>
                  <div class="col s12 m4">
                    <div class="row">
                      {{ form.discount_value_type|materializecss:"input-field s12" }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  {{ form.type|materializecss:"input-field s12" }}
                </div>
                {% for form_type, form in type_base_forms.items %}
                  <div class="row voucher-form" data-type="{{ form_type }}">
                    {% for field in form %}
                      {{ field|materializecss:"input-field s12" }}
                    {% endfor %}
                  </div>
                {% endfor %}
              </div>
              <div class="col s12 m4">
                <div class="row">
                  {{ form.start_date|materializecss:"input-field s12" }}
                </div>
                <div class="row">
                  {{ form.end_date|materializecss:"input-field s12" }}
                </div>
                <div class="row">
                  {{ form.usage_limit|materializecss }}
                </div>
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            {% if voucher.pk %}
              <a href="{% url 'dashboard:voucher-list' %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect waves-light">
                {% trans "Update" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:voucher-list' %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect waves-light">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% endblock %}