saleor_pos/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

saleor_pos/saleor/dashboard/sites/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='site-index'),
    url(r'^(?P<site_id>[0-9]+)/edit/$', views.update, name='site-update'),
]

saleor_pos/saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .search.urls import urlpatterns as search_urls
from .sites.urls import urlpatterns as site_urls
from .shipping.urls import urlpatterns as shipping_urls
from .users.urls import urlpatterns as users_urls
from .permgroups.urls import urlpatterns as group_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^users/', include(users_urls)),
    url(r'^perms/', include(group_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^search/', include(search_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
]

saleor_pos/saleor/dashboard/users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import api
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
        # url(r'^$', views.users, name='users'),
        url(r'^$', permission_required('userprofile.view_user', login_url='account_login')
            (views.users), name='users'),
        url(r'^add/$', permission_required('userprofile.add_user', login_url='account_login')
            (views.user_add), name='user-add'),
        # url(r'^add/$', views.user_add, name='user-add'),
        url(r'^user_process/$', views.user_process, name='user_process'),
        url(r'^detail/(?P<pk>[0-9]+)/$', views.user_detail, name='user-detail'),
        url(r'^delete/(?P<pk>[0-9]+)/$', views.user_delete, name='user-delete'),
        url(r'^edit/(?P<pk>[0-9]+)/$', views.user_edit, name='user-edit'),
        url(r'^user_update(?P<pk>[0-9]+)/$', views.user_update, name='user-update'),
        url(r'^user_assign_permission/$', views.user_assign_permission, name='user_assign_permission'),
        # url(r'^add/', permission_required('userprofile.add_user', login_url='account_login')(views.user_add)),
        
]

if settings.DEBUG:
    # urlpatterns += [ url(r'^static/(?P<path>.*)$', serve)] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor_pos/saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
   
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor_pos/saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor_pos/saleor/dashboard/category/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...product.models import Category
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
        categories = root.get_children()
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal_edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-list', kwargs={'root_pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(request,
                            'dashboard/category/modal_delete.html',
                            ctx)

saleor_pos/saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from ..views import staff_member_required
from ...core.utils import get_paginator_items
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))
    customers = get_paginator_items(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor_pos/saleor/dashboard/discount/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...discount.models import Sale, Voucher
from . import forms


@staff_member_required
def sale_list(request):
    sales = Sale.objects.prefetch_related('products')
    ctx = {'sales': sales}
    return TemplateResponse(request, 'dashboard/discount/sale_list.html', ctx)


@staff_member_required
def sale_edit(request, pk=None):
    if pk:
        instance = get_object_or_404(Sale, pk=pk)
    else:
        instance = Sale()
    form = forms.SaleForm(
        request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save()
        msg = pgettext_lazy(
            'Sale (discount) message', 'Updated sale') if pk else pgettext_lazy(
                'Sale (discount) message', 'Added sale')
        messages.success(request, msg)
        return redirect('dashboard:sale-update', pk=instance.pk)
    ctx = {'sale': instance, 'form': form}
    return TemplateResponse(request, 'dashboard/discount/sale_form.html', ctx)


@staff_member_required
def sale_delete(request, pk):
    instance = get_object_or_404(Sale, pk=pk)
    if request.method == 'POST':
        instance.delete()
        messages.success(
            request,
            pgettext_lazy('Sale (discount) message', 'Deleted sale %s') % (instance.name,))
        return redirect('dashboard:sale-list')
    ctx = {'sale': instance}
    return TemplateResponse(
        request, 'dashboard/discount/sale_modal_confirm_delete.html', ctx)


@staff_member_required
def voucher_list(request):
    vouchers = Voucher.objects.select_related('product', 'category')
    ctx = {'vouchers': vouchers}
    return TemplateResponse(
        request, 'dashboard/discount/voucher_list.html', ctx)


@staff_member_required
def voucher_edit(request, pk=None):
    if pk is not None:
        instance = get_object_or_404(Voucher, pk=pk)
    else:
        instance = Voucher()
    voucher_form = forms.VoucherForm(request.POST or None, instance=instance)
    type_base_forms = {
        Voucher.SHIPPING_TYPE: forms.ShippingVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.SHIPPING_TYPE),
        Voucher.VALUE_TYPE: forms.ValueVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.VALUE_TYPE),
        Voucher.PRODUCT_TYPE: forms.ProductVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.PRODUCT_TYPE),
        Voucher.CATEGORY_TYPE: forms.CategoryVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.CATEGORY_TYPE)}
    if voucher_form.is_valid():
        voucher_type = voucher_form.cleaned_data['type']
        form_type = type_base_forms.get(voucher_type)
        if form_type is None:
            instance = voucher_form.save()
        elif form_type.is_valid():
            instance = form_type.save()

        if form_type is None or form_type.is_valid():
            msg = pgettext_lazy(
                'Voucher message', 'Updated voucher') if pk else pgettext_lazy(
                    'Voucher message', 'Added voucher')
            messages.success(request, msg)
            return redirect('dashboard:voucher-update', pk=instance.pk)
    ctx = {
        'voucher': instance, 'default_currency': settings.DEFAULT_CURRENCY,
        'form': voucher_form, 'type_base_forms': type_base_forms}
    return TemplateResponse(
        request, 'dashboard/discount/voucher_form.html', ctx)


@staff_member_required
def voucher_delete(request, pk):
    instance = get_object_or_404(Voucher, pk=pk)
    if request.method == 'POST':
        instance.delete()
        messages.success(
            request,
            pgettext_lazy('Voucher message', 'Deleted voucher %s') % (instance,))
        return redirect('dashboard:voucher-list')
    ctx = {'voucher': instance}
    return TemplateResponse(
        request, 'dashboard/discount/voucher_modal_confirm_delete.html', ctx)

saleor_pos/saleor/dashboard/search/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.shortcuts import render

from ...order.models import Order
from ...product.models import Product
from ...search.views import paginate_results
from ...userprofile.models import User
from .forms import DashboardSearchForm


@staff_member_required
def search(request):
    form = DashboardSearchForm(data=request.GET or None)
    query = ''
    queryset_map = {
        Product: Product.objects.prefetch_related('images'),
        Order: Order.objects.prefetch_related('user'),
        User: User.objects.all()}
    if form.is_valid():
        results = form.search(queryset_map=queryset_map)
        page = paginate_results(results, request.GET, settings.PAGINATE_BY)
        query = form.cleaned_data['q']
    else:
        page = []
    ctx = {
        'form': form,
        'query': query,
        'results': page,
        'query_string': '?q=%s' % query}
    return render(request, 'dashboard/search/results.html', ctx)

saleor_pos/templates/dashboard/users/detail.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load prices_i18n %}

{% block title %}
  users
{% endblock %}

{% block menu_user_class %}active{% endblock %}
{% block custom_css %}
<style type="text/css">

</style>
{% endblock %}

{% block content %}
<div class="row">
      <div class="panel panel-flat">
        <div class="panel-heading">
          <div class="heading-elements">
            <ul class="icons-list">              
              <li><a data-action="collapse"></a></li>       
              <li><a data-action="close"></a></li>
            </ul>
          </div>
        </div>
        <div class="panel-body">
		    <div class="col-md-6 col-xs-12 left text-center">
		      <div class="left">
			        {% if user.image %}
					<img src=" {{user.image.url}}" alt="Texto Alternativo" class="img-circle img-thumbnail" style="width: 200px;height: 200px;" />
			       {% else %}
			          <img src="{% static 'images/user.png' %}" alt="" class="img-circle img-thumbnail" style="width: 100px;height: 100px;" />
			       {% endif %}
			       <h1>{{user.name }}</h1>
			       <span>{% if user.is_superuser == True %}
                    Admin : {% if user.is_active == True %} (active) {% else %} (inactive) {% endif %}
                 {% else %} 
                    Staff : {% if user.is_active == True %} (active) {% else %} (inactive) {% endif %}
                 {% endif %}</span>
                 <br />
                 <span>Can Login : {% if user.is_staff == True %} (granted) {% else %} (denied) {% endif %}</span>
			    </div>
		       <div class="right">
			      <p> Email: {{user.email }}</p>
			      <p> National ID No: {{user.nid }}</p>
			      <p> Mobile No: {{user.mobile }}</p>  
		       </div>
		     </div> 
         <div class="col-md-6 col0xs-12">
          {% if groups %}
            <h2>Groups</h2>
            {% for group in groups %}
            <li>{{ group.name }}</li>
            {% endfor %}
          {% else %}
              <li>No groups assigned</li>
          {% endif %}
         <h2> Permissions 
            <a href="{% url 'dashboard:user-edit' pk=user.pk %}" class="btn btn-default btn-sm"><i class="icon-pencil7" style="font-size: 11px;"></i> edit</a>
         </h2>
         {% if permissions %}
           {% for permission in permissions %}
           <li>{{ permission.name }}</li>
           {% endfor %}
          {% else %}
          <li>No permissions assigned</li>
          {% endif %}
         </div> 
   </div>
  </div>   
  </div>
</div>
{% endblock %}

saleor_pos/templates/dashboard/users/users.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load prices_i18n %}

{% block title %}
  users
{% endblock %}

{% block menu_user_class %}active{% endblock %}
 {% block custom_css %}
   <style type="text/css">
     .clickable-row td.td{
      cursor: pointer;
     }
   </style>
 {% endblock %}

{% block content %}
 <div class="row">
  <div class="col s12">
	<h2>Users</h2>
    
      <!-- Header and footer fixed -->
      <div class="panel panel-flat">
        <div class="panel-heading">        
          {#{% include "dashboard/includes/_pagination.html" with page_obj=products %}#}
          <div class="heading-elements">
            <ul class="icons-list">              
              <li><a data-action="collapse"></a></li>       
              <li><a data-action="close"></a></li>
            </ul>
          </div>
        </div>
        <div class="table-responsive">
         

        	<table class="table table-bordered datatable-header-footer">
        		<caption style="margin-bottom: 10px;">
            {% if perms.userprofile.add_user %}
               <a href="{% url 'dashboard:user-add' %}" class="btn btn-primary waves-effect waves-light">Add User</a>
            {% endif %}

              {#{% for p in request.user.get_all_permissions %}#}
              {#{{p}}#}
              {#{% endfor %}#}

        		 </caption> 
                <thead style="border-top:1px solid #ddd;">
                  <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>User Role</th>
                    {% if perms.userprofile.change_user or perms.userprofile.delete_user %}
                    <th class="text-center">Actions</th>
                    {% endif %}
                  </tr>
                </thead>
                <tfoot>
                   <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>User Name</th>
                    <th>Email</th>
                    <th>User Role</th>
                    {% if perms.userprofile.change_user or perms.userprofile.delete_user %}
                    <th class="text-center">Actions</th>
                    {% endif %}
                  </tr>
                </tfoot>
                <tbody id="tb">           
               {% if users %}
                  {% for user in users%}
                  <tr class='clickable-row' id="{{user.pk }}">
                    <td class="td" data-href="{% url 'dashboard:user-detail' pk=user.pk %}">#{{ forloop.counter }}</td>
                    <!-- image -->
                   <td class="td" data-href="{% url 'dashboard:user-detail' pk=user.pk %}">
                   {% if user.image %}
                      <img src="{{user.image.url }}" alt="" class="circle teal img-responsive img-circle" style="width: 40px;height: 40px;"/>
                   {% else %}
                      <img src="{% static 'images/user.png' %}" alt="" class="circle teal" style="width: 40px;height: 40px;">
                   {% endif %}
                     <!-- product name -->
                    <td class="td" data-href="{% url 'dashboard:user-detail' pk=user.pk %}">{{user.name}}</td>
                    <!-- product category -->
                    <td class="td" data-href="{% url 'dashboard:user-detail' pk=user.pk %}">{{user.email}}
                    </td>
                    <!-- role -->
                    <td class="td" data-href="{% url 'dashboard:user-detail' pk=user.pk %}"> 
                    {% if user.is_superuser == True %}admin{% else %} staff {% endif %}</td>
                    <!-- actions -->
                    <td class="text-center">
                      <ul class="icons-list">
                       {% if perms.userprofile.change_user %}
                        <li><a href="{% url 'dashboard:user-edit' pk=user.pk %}" class="btn btn-default btn-sm"><i class="icon-pencil7" style="font-size: 11px;"></i> edit</a></li>
                        {% endif %}
                         {% if perms.userprofile.delete_user %}
                        <li>
                          <a data-ta="#modal_instance" data-title="Delete user {{ user.name }} ?" data-href="{% url 'dashboard:user-delete' pk=user.pk %}" data-name="{{ user.name }}" data-id="{{ user.pk }}"
                         class="modal-trigger btn btn-default btn-sm del-btn"><i class="icon-trash" style="font-size: 11px;" href="#modal_instance" data-toggle="modal"></i> remove
                         </a>
                        </li>
                        {% endif %}
                      </ul>
                    </td>
                  </tr>
                  {% endfor %}
                {% else %}
                   <tr><td colspan="6"><h2 class="text-center">no users available</h2></td></tr>
               {% endif %}
                  </tbody>

           </table>

        </div>
      </div>
 
  </div>
</div>

<!-- Blue modal -->
 <div id="modal_instance" class="modal fade">
   <div class="modal-dialog modal-sm">
     <div class="modal-content">
       <div class="modal-header bg-blue">
         <button type="button" class="close" data-dismiss="modal">&times;</button>
         <h6 class="modal-title text-white text-center"></h6>
       </div>
       <div class="modal-body">
         <div class="">
         <form action="" class="delete_form" method="post" id="delform" novalidate>
         {% csrf_token %}
         <div class="">
           <h5 class="text-center">
             Confirm user delete!
           </h5>
           <input type="hidden" class="item-id" />
           </div>
           
         </div>
       </div>
       
       <div class="modal-footer">
         <button type="submit" id='modal_delete' class="btn pull-right bg-danger del" onclick="return false" data-id="" data-href="">Delete</button>
         </form>          
         <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>          
       </div>
     </div>
   </div>
 </div>
 <!-- /blue modal -->
{% endblock%}
{% block custom_js %}
<script type="text/javascript">
// $(".toggle").click(function () {
//     if($(this).hasClass("inactive")){
//         $(this).html('deactivate');
//         $(this).removeClass('inactive');
//         $(this).addClass('activate');
//     }
//     else {
//         $(this).html('activate');
//         $(this).removeClass('activate');
//         $(this).addClass('inactive');
//     }
// });

  $(document).ready(function() {
        $(".td").click(function() {
            window.location = $(this).data("href");
        });

      $('.modal-trigger').on('click', function (e) {

         var url = $(this).data('href')
         var prompt_text = $(this).data('title');
         var username = $(this).data('name');
         var modal = $(this).data('ta');
         var id = $(this).data('id');
         $('.del').attr('data-id', id);
         $('.del').attr('data-href', url);
         $('.modal-title').html(prompt_text);
         $(modal).modal();
         $('.delete_form').attr('action',url);
      });

         /* clicked the submit button */
            $('.del').on('click', function (e) {
                var f = document.getElementById('delform');
                var formData = new FormData(f);
                var id = $(this).data('id');
                var url = $(this).data('href');
                $.ajax({
                    url: url,
                    type: "POST",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success:function(data){        
                      $('#modal_instance').modal('hide');
                      $('#tb #'+id).remove();            
                      $.jGrowl('User deleted successfully', {
                        header: 'Well done!',
                        theme: 'bg-success'
                      });
                      window.location.reload();
                   // $("#mydiv").load(location.href + " #mydiv");
                    },
                    error:function(error){
                      console.log(error);
                      $.jGrowl('Error deleting Staff', {
                          header: 'Oh snap!',
                          theme: 'bg-danger'
                      });
                    }
                });
            });

  });

</script>
{% endblock %}